apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  {{- range .Values.httproute.parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace | default $.Release.Namespace }}
  {{- end }}
  hostnames:
  {{- range .Values.httproute.hostnames }}
    - {{ . }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: Prefix
            value: "/"
      backendRefs:
        - name: {{ include "helm.fullname" . }}
          port: 80
