{{/* Backend Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name | default (printf "%s-backend-svc" .Release.Name) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.service.port | default 80 }}
      targetPort: {{ .Values.backend.service.port | default 80 }}

---
{{/* Frontend Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name | default (printf "%s-frontend-svc" .Release.Name) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: {{ .Values.frontend.service.port | default 80 }}
