---
# ─────────────────────────────────────────────────────────────
# ENABLE JWT AUTH
# ─────────────────────────────────────────────────────────────

- name: Enable JWT auth
  ansible.builtin.command: vault auth enable jwt
  environment: "{{ vault_login_credentials }}"
  when: auth_json['jwt/'] is not defined

# ─────────────────────────────────────────────────────────────
# CONFIGURE JWT
# ─────────────────────────────────────────────────────────────

- name: Configure JWT auth
  ansible.builtin.command: >
    vault write auth/jwt/config
      oidc_discovery_url="{{ github_oidc_discovery_url }}"
      bound_issuer="{{ github_oidc_discovery_url }}"
  environment: "{{ vault_login_credentials }}"

# ─────────────────────────────────────────────────────────────
# CREATE JWT ROLE
# ─────────────────────────────────────────────────────────────

- name: Create JWT role payload
  ansible.builtin.copy:
    dest: vault_aws_terraform_jwt_role_destination_file
    mode: "0600"
    content: |
      {
        "role_type": "jwt",
        "bound_audiences": [
          "https://github.com/{{ github_org }}"
        ],
        "user_claim": "sub",
        "bound_claims_type": "glob",
        "bound_claims": {
          "sub": "repo:{{ github_org }}/{{ github_repo }}:*"
        },
        "token_policies": [
          "{{ vault_aws_terraform_policy_name }}"
        ],
        "token_ttl": "1h"
      }

- name: Create JWT role
  ansible.builtin.shell: >
    vault write auth/jwt/role/{{ vault_jwt_role_name }} vault_aws_terraform_jwt_role_destination_file
  environment: "{{ vault_login_credentials }}"

- name: Remove JWT role payload
  ansible.builtin.file:
    path: vault_aws_terraform_jwt_role_destination_file
    state: absent