---
# ─────────────────────────────────────────────────────────────
# CREATE PKI POLICY
# ─────────────────────────────────────────────────────────────

- name: Create PKI policy
  community.hashi_vault.vault_write:
    path: sys/policies/acl/{{ vault_pki_policy_name }}
    data:
      policy: |
        path "pki/sign/{{ vault_pki_role_name }}" {
          capabilities = ["update"]
        }

        path "pki/cert/ca" {
          capabilities = ["read"]
        }

        path "pki/cert/ca_chain" {
          capabilities = ["read"]
        }

        path "pki/crl" {
          capabilities = ["read"]
        }

        path "sys/mounts" {
            capabilities = ["read"]
        }
  environment: "{{ vault_env }}"

# ─────────────────────────────────────────────────────────────
# CREATE PKI APPROLE
# ─────────────────────────────────────────────────────────────

- name: Create PKI AppRole
  community.hashi_vault.vault_write:
    url: "{{ vault_env.VAULT_ADDR }}"
    token: "{{ vault_env.VAULT_TOKEN }}"
    path: "auth/approle/role/{{ vault_pki_role_name }}"
    data:
      token_policies:
        - "{{ vault_pki_policy_name }}"
      token_ttl: "1h"
      token_max_ttl: "4h"
      secret_id_ttl: "720h"
  no_log: true