---

# Vault role for Terraform / S3 access
aws_account_id: "869868778582"
vault_aws_policy_arns:
  - "arn:aws:iam::{{ aws_account_id }}:policy/jjhealth-services-rds-s3-logs-kms-cache-iam-secretManager-vault-policy.json"
  - "arn:aws:iam::{{ aws_account_id }}:policy/jjhealth-services-ec2-eks-vault-policy.json"
  

# Vault policy name
vault_policy_name: "terraform-policy"
vault_token_ttl: "1h"



vault_pki_role_name: internal

vault_allowed_domains: internal

vault_tls_ttl: 720h


#aws role 
vault_admin_role_name:  "{{ project_name }}_vault_admin_role_name" 
vault_aws_role_name: "{{ project_name }}_pki_client"

vault_pki_gen_role_name: "{{ project_name }}_pki_general"
