---
# ─────────────────────────────────────────────────────────────
# WAIT FOR VAULT TO BE UNSEALED (auto-unseal via KMS)
# ─────────────────────────────────────────────────────────────

- name: Wait for Vault to be unsealed
  ansible.builtin.uri:
    url: "https://{{ vault_dns_name }}:8200/v1/sys/health"
    status_code: [200]
  register: vault_health
  retries: 15
  delay: 3
  until: vault_health.status == 200
  environment:
    VAULT_ADDR: "https://{{ vault_dns_name }}:8200"

- name: Login using AWS auth
  ansible.builtin.command: >
    vault login
    -method=aws
    -format=json
    role="{{ vault_client_pki_role_name }}"
  environment:
    VAULT_ADDR: "https://{{ vault_dns_name }}:8200"
  register: aws_login
  changed_when: false
  failed_when: false
  no_log: true

- name: Extract client token
  ansible.builtin.set_fact:
    vault_token: "{{ (aws_login.stdout | from_json).auth.client_token }}"
  when: aws_login.rc == 0
  no_log: true


- name: Set Vault environment with root token
  ansible.builtin.set_fact:
    vault_login_credentials:
      VAULT_ADDR: "https://{{ vault_dns_name }}:8200"
      VAULT_TOKEN: "{{ vault_token }}"
  no_log: true

  