---
- name: Create TLS directory
  ansible.builtin.file:
    path: "{{ vault_tls_directory }}"
    state: directory
    mode: "0700"

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ vault_tls_private_key }}"
    size: 4096
    type: RSA
    mode: "0600"