# Nginx for Laravel
FROM nginx:alpine

WORKDIR /var/www/html

# Copy only public folder
COPY ./application/public /var/www/html/public

COPY application/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
