{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}-main-config"
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jjhealth-services-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
      server {
        listen 80;
        server_name _;

        root /var/www/html/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
      }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.otelCollector.namespace }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
 
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
      batch:
        timeout: 5s
      filter/dropempty:
        error_mode: ignore
        metrics:
          datapoint:
            - 'value_int == 0'
            - 'value_double == 0.0'
 
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
      debug:
        verbosity: basic
      otlphttp/grafana:
        endpoint: {{ .Values.otelCollector.grafana.endpoint }}
        headers:
          Authorization: "Basic {{ .Values.otelCollector.grafana.auth }}"
 
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, filter/dropempty, batch]
          exporters: [prometheus, otlphttp/grafana, debug]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/grafana, debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/grafana, debug]


