apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: "{{ .Values.configMap.name }}-nginx-config"


      containers:
        - name: php-fpm
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          

          envFrom:
            - configMapRef:
                name: "{{ .Values.configMap.name }}-main-config"
            - secretRef:
                name: {{ .Values.awsSecretsManager.k8sSecretName }}
            - secretRef:
                name: {{ .Values.secret.name }}

        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

            
