{{- if .Values.awsSecretsManager.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsSecretsManager.region }}
      
---
apiVersion:  external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.awsSecretsManager.k8sSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.awsSecretsManager.refreshInterval }}
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.awsSecretsManager.k8sSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME 
      remoteRef:
        key: {{ .Values.awsSecretsManager.secretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.awsSecretsManager.secretName }}
        property: password
{{- end }}
