{{- if .Values.awsSecretsManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: development
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsSecretsManager.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.awsSecretsManager.k8sSecretName }}
  namespace: development
spec:
  refreshInterval: {{ .Values.awsSecretsManager.refreshInterval }}
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.awsSecretsManager.k8sSecretName }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.awsSecretsManager.secretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.awsSecretsManager.secretName }}
        property: password
{{- end }}
