apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jjhealth-frontend-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx" # Assuming NGINX Ingress controller
spec:
  rules:
    - host: jjhealth-services.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jjhealth-frontend
                port:
                  number: 80


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onet-gaming-cert
  namespace: default
spec:
  secretName: onet-gaming-tls   # Cert will be stored here
  dnsNames:
    - onet-gaming.com
    - www.onet-gaming.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: you@onet-gaming.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx

