apiVersion: v1
kind: Secret
metadata:
  name: jjhealth-services-secret
  namespace: development
type: Opaque
stringData:
  APP_KEY: "base64:bIys/xG8FSOy0KL6ttG3AZUwg/dq66PnIUOzlVfotzs="
  DB_PASSWORD: "Sonship123$"
  REDIS_PASSWORD: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
