---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jjhealth-services-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/john1234567987/jjhealth-services.git
    targetRevision: main
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
