apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Optional: Set production-specific namespace, labels, etc.
namespace: development

images:
- name: ghcr.io/anigbojohnson/jjhealth-backend
  newName: ghcr.io/anigbojohnson/jjhealth-backend
  newTag: 8079078b52ce8373db2c0fec9d9f54f46a27526c

# Delete HPA in development
patches:
- path: patch-backend-replicas.yaml
  target:
    kind: Deployment
    name: jjhealth-backend
- path: delete-hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
