apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Optional: Set production-specific namespace, labels, etc.
namespace: development

images:
- name: ghcr.io/anigbojohnson/jjhealth-backend
  newName: ghcr.io/anigbojohnson/jjhealth-backend
  newTag: 0719cfb4b9ee716c62ef0cca919a954a1cfed0f9

# Delete HPA in development
patches:
- path: patch-backend-replicas.yaml
  target:
    kind: Deployment
    name: jjhealth-backend
- path: delete-hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
