apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Optional: Set production-specific namespace, labels, etc.
namespace: development

images:
- name: ghcr.io/anigbojohnson/jjhealth-backend
  newName: ghcr.io/anigbojohnson/jjhealth-backend
  newTag: d87d5874f70239552ada5160eed6d3d7225ecb9e

# Delete HPA in development
patches:
- path: patch-backend-replicas.yaml
  target:
    kind: Deployment
    name: jjhealth-backend
- path: delete-hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
