---
- name: Configure AWS auth role
  community.hashi_vault.vault_write:
    url: "{{ vault_env.VAULT_ADDR }}"
    token: "{{ vault_env.VAULT_TOKEN }}"
    path: "auth/{{ vault_aws_auth_mount }}/role/{{ vault_aws_role_name }}"
    data:
      auth_type: iam
      bound_iam_principal_arn: "{{ backend_instance_role_arn }}"
      token_policies:
        - "{{ vault_pki_policy_name }}"
      token_ttl: 1h