---
# ─────────────────────────────────────────────────────────────
# CREATE PKI POLICY
# ─────────────────────────────────────────────────────────────

- name: Create PKI policy file
  ansible.builtin.copy:
    dest: /tmp/pki-policy.hcl
    owner: root
    group: root
    mode: "0600"
    content: |
      # Issue certificates
      path "pki/sign/{{ vault_pki_role_name }}" {
        capabilities = ["update"]
      }

      # Read the Root CA certificate
      path "pki/cert/ca" {
        capabilities = ["read"]
      }

      # Read the CA chain
      path "pki/cert/ca_chain" {
        capabilities = ["read"]
      }

      # Read the CRL
      path "pki/crl" {
        capabilities = ["read"]
      }
      path "pki/issue/{{ vault_pki_role_name }}" {
        capabilities = ["update"]
      }

# ─────────────────────────────────────────────────────────────
# APPLY POLICY
# ─────────────────────────────────────────────────────────────


- name: Apply PKI policy
  ansible.builtin.command: >
    vault policy write
      {{ vault_pki_policy_name }}
      /tmp/pki-policy.hcl
  environment: "{{ vault_env_root_token }}"

# ─────────────────────────────────────────────────────────────
# REMOVE TEMPORARY POLICY FILE
# ─────────────────────────────────────────────────────────────

- name: Remove PKI policy file
  ansible.builtin.file:
    path: /tmp/pki-policy.hcl
    state: absent

# ─────────────────────────────────────────────────────────────
# CONFIGURE AWS AUTH ROLE 
# ─────────────────────────────────────────────────────────────
- name: Configure AWS auth role
  community.hashi_vault.vault_write:
    url: "{{ vault_env_root_token.VAULT_ADDR }}"
    token: "{{ vault_env_root_token.VAULT_TOKEN }}"
    path: "auth/aws/role/{{ vault_aws_role_name }}"
    data:
      auth_type: iam
      bound_iam_principal_arn: "{{ vault_instance_role_arn }}"
      token_policies:
        - "{{ vault_pki_policy_name }}"
      token_ttl: 1h
        