---
# ============================================================================
# CREATE PEM BUNDLE
# ============================================================================

- name: Create CA PEM bundle
  ansible.builtin.shell: |
    cat "{{ vault_tls_ca_private_key }}" "{{ vault_tls_ca_certificate }}" > /tmp/vault-ca-bundle.pem
  args:
    creates: "{{ ca_pem_bundle}}"

- name: Read PEM bundle
  ansible.builtin.slurp:
    src: "{{ ca_pem_bundle }}"
  register: vault_ca_bundle

# ============================================================================
# IMPORT EXISTING CA
# ============================================================================

- name: Import existing CA
  community.hashi_vault.vault_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_login_credentials.VAULT_TOKEN }}"
    path: "pki/config/ca"
    data:
      pem_bundle: "{{ vault_ca_bundle.content | b64decode }}"

# ============================================================================
# CONFIGURE URLS
# ============================================================================

- name: Configure PKI URLs
  community.hashi_vault.vault_write:
    url: "{{ vault_login_credentials.VAULT_ADDR }}"
    token: "{{ vault_login_credentials.VAULT_TOKEN }}"
    path: "pki/config/urls"
    data:
      issuing_certificates: "{{ vault_login_credentials.VAULT_ADDR }}/v1/pki/ca"
      crl_distribution_points: "{{ vault_login_credentials.VAULT_ADDR }}/v1/pki/crl"

# ============================================================================
# CREATE PKI ROLE FOR CLIENT CERTIFICATES
# ============================================================================

- name: Create PKI role for internal machines
  community.hashi_vault.vault_write:
    url: "{{ vault_login_credentials.VAULT_TOKEN }}"
    token: "{{ vault_login_credentials.VAULT_TOKEN }}"
    path: "pki/roles/internal"
    data:
      allowed_domains:
        - "{{ vault_dns_name.split('.', 1)[1] }}"
      allow_subdomains: true
      allow_bare_domains: true
      allow_localhost: true
      allow_ip_sans: true
      enforce_hostnames: true
      server_flag: true
      client_flag: true
      key_type: rsa
      key_bits: 4096
      max_ttl: "720h"

