# ─────────────────────────────────────────────────────────────
# CHECK EXISTING SECRETS ENGINES
# ─────────────────────────────────────────────────────────────

- name: Check secrets engines
  ansible.builtin.command: vault secrets list -format=json
  environment: "{{ vault_env_root_token }}"
  register: secrets_list
  changed_when: false

- name: Parse secrets engines
  ansible.builtin.set_fact:
    secrets_json: "{{ secrets_list.stdout | from_json }}"

# ─────────────────────────────────────────────────────────────
# ENABLE PKI SECRETS ENGINE
# ─────────────────────────────────────────────────────────────
- name: Enable PKI secrets engine
  community.hashi_vault.vault_write:
    url: "{{  vault_login_credentials.VAULT_ADDR }}"
    token: "{{  vault_login_credentials.VAULT_TOKEN }}"
    path: "sys/mounts/pki"
    data:
      type: pki
      description: Internal PKI
      config:
        max_lease_ttl: "87600h"
  when: secrets_json['pki/'] is not defined