---

# PKI
vault_pki_mount: "pki"
vault_pki_role_name: "internal"
vault_pki_policy_name: "pki-client"


#Certificate Authority Details
vault_root_ca_secret_name: jjhealth-services/vault/root-ca


#Files
vault_tls_ca_private_key: "{{ tls_dir}}/server.key"
vault_tls_ca_certificate: "{{ tls_dir}}/server.crt"
ca_pem_bundle: /tmp/vault-ca-bundle.pem