name: CI/CD - Build & Deploy JJHealth

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    outputs:
      backend_image: ghcr.io/${{ github.repository_owner }}/jjhealth-backend:latest
      frontend_image: ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jjhealth-backend:latest
            ghcr.io/${{ github.repository_owner }}/jjhealth-backend:${{ github.sha }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:latest
            ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:${{ github.sha }}

  deploy:
    name: Deploy to EKS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Change this to your EKS region

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name your-cluster-name

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Helm Lint
        run: |
          helm lint kubernetes/helm

      - name: Helm Deploy
        run: |
          helm upgrade --install jjhealth kubernetes/helm \
            --namespace jjhealth \
            --create-namespace \
            --set backend.image.repository=ghcr.io/${{ github.repository_owner }}/jjhealth-backend \
            --set backend.image.tag=${{ github.sha }} \
            --set backend.image.pullPolicy=IfNotPresent \
            --set frontend.image.repository=ghcr.io/${{ github.repository_owner }}/jjhealth-frontend \
            --set frontend.image.tag=${{ github.sha }} \
            --set frontend.image.pullPolicy=IfNotPresent
