name: CI/CD - Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    outputs:
      backend_image: ghcr.io/${{ github.repository_owner }}/jjhealth-backend:latest
      frontend_image: ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jjhealth-backend:latest
            ghcr.io/${{ github.repository_owner }}/jjhealth-backend:${{ github.sha }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:latest
            ghcr.io/${{ github.repository_owner }}/jjhealth-frontend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Print image outputs
        run: |
          echo "Backend image: ${{ needs.build-and-push.outputs.backend_image }}"
          echo "Frontend image: ${{ needs.build-and-push.outputs.frontend_image }}"

       
      - name: Print image outputs
        run: |
          echo "Backend image: ${{ needs.build-and-push.outputs.backend_image }}"
          echo "Frontend image: ${{ needs.build-and-push.outputs.frontend_image }}"
