name: Terraform Deployment

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/root

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://13.40.85.203:8200
          role: gh-actions-role
          jwtGithubAudience: https://github.com/anigbojohnson
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY;
            aws/creds/terraform-role security_token | AWS_SESSION_TOKEN
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Clean Terraform Directory
        run: rm -rf .terraform

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform State List
        run: terraform state list

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform aply -auto-approve
