name: Terraform Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/root


    steps:
      - uses: actions/checkout@v4

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://18.175.123.215:8200
          role: gh-actions-role
          jwtGithubAudience: https://github.com/anigbojohnson
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - uses: hashicorp/setup-terraform@v3
      - run: rm -rf .terraform
      - run: terraform init
      - run: terraform plan -out=tfplan
      - run: terraform destroy -auto-approve -input=false tfplan

      