name: Terraform deployment for jjhealth infrastructure 

on:
  push:
    branches: [dev]
    paths:
      - 'terraform/app/**'
      - '.github/workflows/terraform-ci.yml'

  pull_request:
    branches: [main]
    paths:
      - 'terraform/app/'

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: 
      - self-hosted
      - linux
      - x64
    defaults:
      run:
        working-directory: terraform/app/

    steps:
      - uses: actions/checkout@v4


      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://10.0.2.235:8200
          role: gh-actions-role
          jwtGithubAudience: https://github.com/anigbojohnson
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY;

      - name: Wait for AWS credentials to propagate
        run: sleep 10

      - name: Clean Terraform Directory
        run: rm -rf .terraform

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve


