name: Vault provisioning and configuration using terraform and ansible
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/vault/**'
      - 'vault/**'
      - '.github/workflows/vault-ci.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.filter.outputs.vault }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            vault:
              - 'terraform/vault/**'


  terraform:
    needs: detect-changes
    if: needs.detect-changes.outputs.terraform_changed == 'true'
    runs-on: ubuntu-latest

   
    defaults:
      run:
        working-directory: terraform/vault/

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869868778582:role/GitHubTerraformRole
          aws-region: eu-west-2

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
  ansible:
    needs:
      - detect-changes
      - terraform
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869868778582:role/GitHubTerraformRole
          aws-region: eu-west-2

      - name: Install Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible

      - name: Install boto3 for Ansible
        run: |
          pipx inject ansible-core boto3 botocore 2>/dev/null || \
          python3 -m pip install boto3 botocore --break-system-packages

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r vault/requirements.yml

      - uses: hashicorp/setup-terraform@v3

      - name: Read Terraform Output
        working-directory: terraform/vault
        run: |
          terraform init
          echo "VAULT_KMS_KEY_ID=$(terraform output -raw vault_kms_key_id)" >> $GITHUB_ENV
          echo "VAULT_PRIVATE_IP=$(terraform output -raw vault_private_ip)" >> $GITHUB_ENV
          echo "BASTION_PUBLIC_IP=$(terraform output -raw bastion_public_ip)" >> $GITHUB_ENV
          echo "SSM_BUCKET_NAME=$(terraform output -raw ssm_transfer_bucket_name)" >> $GITHUB_ENV

      - name: Test bastion
        run: |
          echo "Testing bastion SSH"
          nc -vz ${BASTION_PUBLIC_IP} 22 || echo "Bastion port 22 blocked"
        


      - name: Test ProxyJump to Vault
        run: |
          ssh -i ${GITHUB_WORKSPACE}/vault/vault-key.pem \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o ConnectTimeout=15 \
              -o ProxyCommand="ssh -i ${GITHUB_WORKSPACE}/vault/vault-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@${BASTION_PUBLIC_IP}" \
              ubuntu@${VAULT_PRIVATE_IP} "echo 'Vault SSH OK'"
              
      - name: Generate Ansible Inventory
        working-directory: vault
        run: |
          chmod 600 ${GITHUB_WORKSPACE}/vault/vault-key.pem
          cat > inventory.ini <<EOF
          [vault_servers]
          vault-ec2 ansible_host=${VAULT_PRIVATE_IP} ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=${GITHUB_WORKSPACE}/vault/vault-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ${GITHUB_WORKSPACE}/vault/vault-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@${BASTION_PUBLIC_IP}"'
          EOF
              cat inventory.ini

      - name: Debug Outputs
        run: |
          echo "BASTION_PUBLIC_IP=${BASTION_PUBLIC_IP}"
          echo "VAULT_PRIVATE_IP=${VAULT_PRIVATE_IP}"

      - name: Run Ansible Playbook
        working-directory: vault
        run: |
          ansible-playbook -i inventory.ini site.yml \
            -e vault_kms_key_id=${{ env.VAULT_KMS_KEY_ID }}
        



