name: Vault provisioning and configuration using terraform and ansible
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/vault/**'
      - 'vault/**'
      - '.github/workflows/vault-ci.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.filter.outputs.vault }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            vault:
              - 'terraform/vault/**'


  terraform:
    needs: detect-changes
    if: needs.detect-changes.outputs.terraform_changed == 'true'
    runs-on: ubuntu-latest

   
    defaults:
      run:
        working-directory: terraform/vault/

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869868778582:role/GitHubTerraformRole
          aws-region: eu-west-2

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
  ansible:
    needs:
      - detect-changes
      - terraform
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869868778582:role/GitHubTerraformRole
          aws-region: eu-west-2

      - name: Install Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible

      - name: Install boto3 for Ansible
        run: |
          pipx inject ansible-core boto3 botocore 2>/dev/null || \
          python3 -m pip install boto3 botocore --break-system-packages

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r vault/requirements.yml

      - uses: hashicorp/setup-terraform@v3

      - name: Read Terraform Output
        working-directory: terraform/vault
        run: |
          terraform init
          echo "VAULT_KMS_KEY_ID=$(terraform output -raw vault_kms_key_id)" >> $GITHUB_ENV
          echo "VAULT_INSTANCE_ID=$(terraform output -raw vault_instance_id)" >> $GITHUB_ENV
          echo "SSM_BUCKET_NAME=$(terraform output -raw ssm_transfer_bucket_name)" >> $GITHUB_ENV

      - name: Generate Ansible Inventory
        run: |
          cat > inventory.ini <<EOF
          [vault_servers]
          vault-ec2 ansible_host=${{ env.VAULT_INSTANCE_ID }} ansible_connection=amazon.aws.aws_ssm ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_aws_ssm_region=eu-west-2 ansible_aws_ssm_bucket_name=${{ env.SSM_BUCKET_NAME }} ansible_remote_tmp=/tmp/.ansible-tmp ansible_aws_ssm_timeout=300
          EOF

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini vault/site.yml \
            -e vault_kms_key_id=${{ env.VAULT_KMS_KEY_ID }}



